worlds: ["world"]
chance: 100
min_complexity: 40
max_complexity: 115
dungeon:
  mob_density: 13
  types: [ZOMBIE,SKELETON,SPIDER,CREEPER,SILVERFISH]
  rewards:
    ZOMBIE:
      - IRON_INGOT:0:2
      - IRON_HELMET:0:1
      - IRON_LEGGINGS:0:1
      - IRON_CHESTPLATE:0:1
      - IRON_BOOTS:0:1
      - GOLDEN_APPLE:0:1
      - OBSIDIAN:0:4
      - POTION:8193:1
      - POTION:8197:1
    SKELETON:
      - BOW:0:1
      - ARROW:0:12
      - BONE:0:2
      - LEATHER_CHESTPLATE:0:1
      - LEATHER_HELMET:0:1
      - LEATHER_BOOTS:0:1
      - LEATHER_LEGGINGS:0:1
      - WOOD_SWORD:0:1
      - POTION:8226:1
    SPIDER:
      - STRING:0:4
      - CHAINMAIL_CHESTPLATE:0:1
      - CHAINMAIL_BOOTS:0:1
      - CHAINMAIL_HELMET:0:1
      - CHAINMAIL_LEGGINGS:0:1
      - STONE_SWORD:0:1
      - POTION:16452:1
    CREEPER:
      - SULPHUR:0:2
      - DIAMOND_BOOTS:0:1
      - DIAMOND_HELMET:0:1
      - DIAMOND_LEGGINGS:0:1
      - DIAMOND_CHESTPLATE:0:1
      - DIAMOND_SWORD:0:1
      - DIAMOND:0:1
      - TNT:0:4
      - FLINT_AND_STEEL:0:1
      - POTION:16428:1
    SILVERFISH:
      - EXP_BOTTLE:0:2
      - GOLD_HELMET:0:1
      - GOLD_CHESTPLATE:0:1
      - GOLD_LEGGINGS:0:1
      - GOLD_BOOTS:0:1
      - GOLD_PICKAXE:0:2
      - GOLD_AXE:0:1
      - GOLD_SPADE:0:2
      - GOLD_SWORD:0:1
      - GOLD_INGOT:0:4
      - POTION:16392:1
      - ENDER_PEARL:0:12
      - EYE_OF_ENDER:0:2